const fs = require('fs');
const file = 'C:/Users/aghaa/Desktop/HRM PRO/frontend/src/app/dashboard/payroll/page.tsx';
let content = fs.readFileSync(file, 'utf8');

// Add auto-generated badge to payroll records
content = content.replace(
  '{record.status ? record.status.charAt(0).toUpperCase() + record.status.slice(1) : "—"}',
  '{record.status ? record.status.charAt(0).toUpperCase() + record.status.slice(1) : "—"}{record.autoGenerated && <span className="ml-1 text-xs bg-blue-100 text-blue-600 px-1.5 py-0.5 rounded-full font-medium">Auto</span>}'
);

fs.writeFileSync(file, content, 'utf8');
console.log('Done!');