import { Injectable, Logger } from '@nestjs/common';
import { Cron } from '@nestjs/schedule';
import { PrismaService } from '../prisma/prisma.service';
import { PayrollService } from './payroll.service';

@Injectable()
export class PayrollScheduler {
    private readonly logger = new Logger(PayrollScheduler.name);
    constructor(
        private prisma: PrismaService,
        private payrollService: PayrollService,
    ) {}

    @Cron('0 9 1 * *') // Run at 9 AM on 1st of every month
    async autoGeneratePayroll() {
        this.logger.log('Running auto payroll generation...');
        const now = new Date();
        const month = now.getMonth() === 0 ? 12 : now.getMonth(); // Previous month
        const year = now.getMonth() === 0 ? now.getFullYear() - 1 : now.getFullYear();

        // Get all active companies
        const companies = await this.prisma.company.findMany({
            where: { status: 'active' },
        });

        for (const company of companies) {
            try {
                // Get all active employees
                const employees = await this.prisma.employee.findMany({
                    where: { companyId: company.id, status: 'active' },
                });

                let generated = 0;
                for (const employee of employees) {
                    // Check if payroll already exists
                    const existing = await this.prisma.payroll.findFirst({
                        where: { companyId: company.id, employeeId: employee.id, month, year },
                    });
                    if (existing) continue;

                    // Create payroll record
                    const basic = employee.salary || 0;
                    const houseRent = Math.round(basic * 0.45);
                    const medicalAllowance = Math.round(basic * 0.1);
                    const transportAllowance = Math.round(basic * 0.05);
                    const grossSalary = basic + houseRent + medicalAllowance + transportAllowance;
                    const eobi = Math.round(basic * 0.01);
                    const netSalary = grossSalary - eobi;

                    await this.prisma.payroll.create({
                        data: {
                            companyId: company.id,
                            employeeId: employee.id,
                            month,
                            year,
                            basic,
                            houseRent,
                            medicalAllowance,
                            transportAllowance,
                            otherAllowances: 0,
                            bonus: 0,
                            overtimePay: 0,
                            grossSalary,
                            withholdingTax: 0,
                            eobi,
                            loanDeduction: 0,
                            otherDeductions: 0,
                            totalDeductions: eobi,
                            netSalary,
                            status: 'pending',
                            autoGenerated: true,
                        },
                    });
                    generated++;
                }
                this.logger.log("Auto payroll generated for company " + company.id + ": " + generated + " records");
            } catch (err) {
                this.logger.error("Error generating payroll for company " + company.id + ": " + err.message);
            }
        }
    }
}