import { Injectable, Logger } from '@nestjs/common';
import { Cron } from '@nestjs/schedule';
import { PrismaService } from '../prisma/prisma.service';
import { PayrollService } from './payroll.service';

@Injectable()
export class PayrollScheduler {
    private readonly logger = new Logger(PayrollScheduler.name);
    constructor(
        private prisma: PrismaService,
        private payrollService: PayrollService,
    ) {}

    @Cron('0 9 1 * *') // Run at 9 AM on 1st of every month
    async autoGeneratePayroll() {
        this.logger.log('Running auto payroll generation...');
        const now = new Date();
        const month = now.getMonth() === 0 ? 12 : now.getMonth();
        const year = now.getMonth() === 0 ? now.getFullYear() - 1 : now.getFullYear();

        const companies = await this.prisma.company.findMany({ where: { status: 'active' } });

        for (const company of companies) {
            try {
                const employees = await this.prisma.employee.findMany({
                    where: { companyId: company.id, status: 'active' },
                });

                let generated = 0;
                for (const employee of employees) {
                    const existing = await this.prisma.payroll.findFirst({
                        where: { companyId: company.id, employeeId: employee.id, month, year },
                    });
                    if (existing) continue;

                    // Use PayrollService to create with proper deductions
                    const adminUser = { role: 'COMPANY_ADMIN', companyId: company.id };
                    await this.payrollService.create({
                        employeeId: employee.id,
                        month,
                        year,
                        basic: employee.salary || 0,
                        houseRent: Math.round((employee.salary || 0) * 0.45),
                        medicalAllowance: Math.round((employee.salary || 0) * 0.1),
                        transportAllowance: Math.round((employee.salary || 0) * 0.05),
                        otherAllowances: 0,
                        bonus: 0,
                        overtimePay: 0,
                        withholdingTax: 0,
                        loanDeduction: 0,
                        otherDeductions: 0,
                        autoGenerated: true,
                    }, company.id, adminUser);
                    generated++;
                }
                this.logger.log("Auto payroll generated for company " + company.id + ": " + generated + " records");
            } catch (err) {
                this.logger.error("Error generating payroll for company " + company.id + ": " + err.message);
            }
        }
    }
}